spring:
  profiles:
    active: local

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true

---
spring:
  profiles: local

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:test
      username: sa
      password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

---
spring:
  profiles: prod

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://210.114.17.188:3306/db_creedit
      username: jjw920418
      password:
      driver-class-name: com.mysql.jdbc.Driver
      max-lifetime: 28000000
      connection-timeout: 10000
      maximum-pool-size: 5

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false

